version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_origem
    restart: unless-stopped
    ports:
      - "5433:5432"
    networks:
      - datalake
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-origem}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../src/01_origem/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./init_extra_dbs.sql:/docker-entrypoint-initdb.d/02_extra_dbs.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
networks:
  datalake:
    external: true